//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wlkg.GetData {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", ConfigurationName="GetData.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 消息 GetClientDataRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetClientData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetClientDataResponse GetClientData(wlkg.GetData.GetClientDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetClientData", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetClientDataResponse> GetClientDataAsync(wlkg.GetData.GetClientDataRequest request);
        
        // CODEGEN: 消息 GetContractInfo_HYGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetContractInfo_" +
            "HYGS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetContractInfo_HYGSResponse GetContractInfo_HYGS(wlkg.GetData.GetContractInfo_HYGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetContractInfo_" +
            "HYGS", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetContractInfo_HYGSResponse> GetContractInfo_HYGSAsync(wlkg.GetData.GetContractInfo_HYGSRequest request);
        
        // CODEGEN: 消息 GetContractInfoByTime_HYGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetContractInfoB" +
            "yTime_HYGS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetContractInfoByTime_HYGSResponse GetContractInfoByTime_HYGS(wlkg.GetData.GetContractInfoByTime_HYGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetContractInfoB" +
            "yTime_HYGS", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetContractInfoByTime_HYGSResponse> GetContractInfoByTime_HYGSAsync(wlkg.GetData.GetContractInfoByTime_HYGSRequest request);
        
        // CODEGEN: 消息 GetContractInfo_CWGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetContractInfo_" +
            "CWGS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetContractInfo_CWGSResponse GetContractInfo_CWGS(wlkg.GetData.GetContractInfo_CWGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetContractInfo_" +
            "CWGS", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetContractInfo_CWGSResponse> GetContractInfo_CWGSAsync(wlkg.GetData.GetContractInfo_CWGSRequest request);
        
        // CODEGEN: 消息 GetContractInfoByTime_CWGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetContractInfoB" +
            "yTime_CWGS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetContractInfoByTime_CWGSResponse GetContractInfoByTime_CWGS(wlkg.GetData.GetContractInfoByTime_CWGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetContractInfoB" +
            "yTime_CWGS", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetContractInfoByTime_CWGSResponse> GetContractInfoByTime_CWGSAsync(wlkg.GetData.GetContractInfoByTime_CWGSRequest request);
        
        // CODEGEN: 消息 GetPayReceiveBill_HYGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetPayReceiveBil" +
            "l_HYGS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetPayReceiveBill_HYGSResponse GetPayReceiveBill_HYGS(wlkg.GetData.GetPayReceiveBill_HYGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetPayReceiveBil" +
            "l_HYGS", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBill_HYGSResponse> GetPayReceiveBill_HYGSAsync(wlkg.GetData.GetPayReceiveBill_HYGSRequest request);
        
        // CODEGEN: 消息 GetPayReceiveBillByTime_HYGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetPayReceiveBil" +
            "lByTime_HYGS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetPayReceiveBillByTime_HYGSResponse GetPayReceiveBillByTime_HYGS(wlkg.GetData.GetPayReceiveBillByTime_HYGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetPayReceiveBil" +
            "lByTime_HYGS", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBillByTime_HYGSResponse> GetPayReceiveBillByTime_HYGSAsync(wlkg.GetData.GetPayReceiveBillByTime_HYGSRequest request);
        
        // CODEGEN: 消息 GetPayReceiveBill_CWGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetPayReceiveBil" +
            "l_CWGS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetPayReceiveBill_CWGSResponse GetPayReceiveBill_CWGS(wlkg.GetData.GetPayReceiveBill_CWGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetPayReceiveBil" +
            "l_CWGS", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBill_CWGSResponse> GetPayReceiveBill_CWGSAsync(wlkg.GetData.GetPayReceiveBill_CWGSRequest request);
        
        // CODEGEN: 消息 GetPayReceiveBillByTime_CWGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetPayReceiveBil" +
            "lByTime_CWGS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetPayReceiveBillByTime_CWGSResponse GetPayReceiveBillByTime_CWGS(wlkg.GetData.GetPayReceiveBillByTime_CWGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetPayReceiveBil" +
            "lByTime_CWGS", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBillByTime_CWGSResponse> GetPayReceiveBillByTime_CWGSAsync(wlkg.GetData.GetPayReceiveBillByTime_CWGSRequest request);
        
        // CODEGEN: 消息 GetYW_HYGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetYW_HYGS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetYW_HYGSResponse GetYW_HYGS(wlkg.GetData.GetYW_HYGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetYW_HYGS", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetYW_HYGSResponse> GetYW_HYGSAsync(wlkg.GetData.GetYW_HYGSRequest request);
        
        // CODEGEN: 消息 GetYWByTime_HYGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetYWByTime_HYGS" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetYWByTime_HYGSResponse GetYWByTime_HYGS(wlkg.GetData.GetYWByTime_HYGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetYWByTime_HYGS" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetYWByTime_HYGSResponse> GetYWByTime_HYGSAsync(wlkg.GetData.GetYWByTime_HYGSRequest request);
        
        // CODEGEN: 消息 GetYW_CWGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetYW_CWGS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetYW_CWGSResponse GetYW_CWGS(wlkg.GetData.GetYW_CWGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetYW_CWGS", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetYW_CWGSResponse> GetYW_CWGSAsync(wlkg.GetData.GetYW_CWGSRequest request);
        
        // CODEGEN: 消息 GetYWByTime_CWGSRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetYWByTime_CWGS" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetYWByTime_CWGSResponse GetYWByTime_CWGS(wlkg.GetData.GetYWByTime_CWGSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetYWByTime_CWGS" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetYWByTime_CWGSResponse> GetYWByTime_CWGSAsync(wlkg.GetData.GetYWByTime_CWGSRequest request);
        
        // CODEGEN: 消息 GetYW_CWGS_CDBRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetYW_CWGS_CDB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wlkg.GetData.GetYW_CWGS_CDBResponse GetYW_CWGS_CDB(wlkg.GetData.GetYW_CWGS_CDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx/GetYW_CWGS_CDB", ReplyAction="*")]
        System.Threading.Tasks.Task<wlkg.GetData.GetYW_CWGS_CDBResponse> GetYW_CWGS_CDBAsync(wlkg.GetData.GetYW_CWGS_CDBRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientData", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetClientDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        public GetClientDataRequest() {
        }
        
        public GetClientDataRequest(wlkg.GetData.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClientDataResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetClientDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetClientDataResult;
        
        public GetClientDataResponse() {
        }
        
        public GetClientDataResponse(System.Data.DataTable GetClientDataResult) {
            this.GetClientDataResult = GetClientDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContractInfo_HYGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetContractInfo_HYGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        public GetContractInfo_HYGSRequest() {
        }
        
        public GetContractInfo_HYGSRequest(wlkg.GetData.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContractInfo_HYGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetContractInfo_HYGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetContractInfo_HYGSResult;
        
        public GetContractInfo_HYGSResponse() {
        }
        
        public GetContractInfo_HYGSResponse(System.Data.DataTable GetContractInfo_HYGSResult) {
            this.GetContractInfo_HYGSResult = GetContractInfo_HYGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContractInfoByTime_HYGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetContractInfoByTime_HYGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public string StartTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=1)]
        public string EndTime;
        
        public GetContractInfoByTime_HYGSRequest() {
        }
        
        public GetContractInfoByTime_HYGSRequest(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            this.AuthHeader = AuthHeader;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContractInfoByTime_HYGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetContractInfoByTime_HYGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetContractInfoByTime_HYGSResult;
        
        public GetContractInfoByTime_HYGSResponse() {
        }
        
        public GetContractInfoByTime_HYGSResponse(System.Data.DataTable GetContractInfoByTime_HYGSResult) {
            this.GetContractInfoByTime_HYGSResult = GetContractInfoByTime_HYGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContractInfo_CWGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetContractInfo_CWGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        public GetContractInfo_CWGSRequest() {
        }
        
        public GetContractInfo_CWGSRequest(wlkg.GetData.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContractInfo_CWGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetContractInfo_CWGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetContractInfo_CWGSResult;
        
        public GetContractInfo_CWGSResponse() {
        }
        
        public GetContractInfo_CWGSResponse(System.Data.DataTable GetContractInfo_CWGSResult) {
            this.GetContractInfo_CWGSResult = GetContractInfo_CWGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContractInfoByTime_CWGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetContractInfoByTime_CWGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public string StartTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=1)]
        public string EndTime;
        
        public GetContractInfoByTime_CWGSRequest() {
        }
        
        public GetContractInfoByTime_CWGSRequest(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            this.AuthHeader = AuthHeader;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContractInfoByTime_CWGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetContractInfoByTime_CWGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetContractInfoByTime_CWGSResult;
        
        public GetContractInfoByTime_CWGSResponse() {
        }
        
        public GetContractInfoByTime_CWGSResponse(System.Data.DataTable GetContractInfoByTime_CWGSResult) {
            this.GetContractInfoByTime_CWGSResult = GetContractInfoByTime_CWGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayReceiveBill_HYGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetPayReceiveBill_HYGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        public GetPayReceiveBill_HYGSRequest() {
        }
        
        public GetPayReceiveBill_HYGSRequest(wlkg.GetData.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayReceiveBill_HYGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetPayReceiveBill_HYGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetPayReceiveBill_HYGSResult;
        
        public GetPayReceiveBill_HYGSResponse() {
        }
        
        public GetPayReceiveBill_HYGSResponse(System.Data.DataTable GetPayReceiveBill_HYGSResult) {
            this.GetPayReceiveBill_HYGSResult = GetPayReceiveBill_HYGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayReceiveBillByTime_HYGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetPayReceiveBillByTime_HYGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public string StartTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=1)]
        public string EndTime;
        
        public GetPayReceiveBillByTime_HYGSRequest() {
        }
        
        public GetPayReceiveBillByTime_HYGSRequest(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            this.AuthHeader = AuthHeader;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayReceiveBillByTime_HYGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetPayReceiveBillByTime_HYGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetPayReceiveBillByTime_HYGSResult;
        
        public GetPayReceiveBillByTime_HYGSResponse() {
        }
        
        public GetPayReceiveBillByTime_HYGSResponse(System.Data.DataTable GetPayReceiveBillByTime_HYGSResult) {
            this.GetPayReceiveBillByTime_HYGSResult = GetPayReceiveBillByTime_HYGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayReceiveBill_CWGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetPayReceiveBill_CWGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        public GetPayReceiveBill_CWGSRequest() {
        }
        
        public GetPayReceiveBill_CWGSRequest(wlkg.GetData.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayReceiveBill_CWGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetPayReceiveBill_CWGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetPayReceiveBill_CWGSResult;
        
        public GetPayReceiveBill_CWGSResponse() {
        }
        
        public GetPayReceiveBill_CWGSResponse(System.Data.DataTable GetPayReceiveBill_CWGSResult) {
            this.GetPayReceiveBill_CWGSResult = GetPayReceiveBill_CWGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayReceiveBillByTime_CWGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetPayReceiveBillByTime_CWGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public string StartTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=1)]
        public string EndTime;
        
        public GetPayReceiveBillByTime_CWGSRequest() {
        }
        
        public GetPayReceiveBillByTime_CWGSRequest(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            this.AuthHeader = AuthHeader;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPayReceiveBillByTime_CWGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetPayReceiveBillByTime_CWGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetPayReceiveBillByTime_CWGSResult;
        
        public GetPayReceiveBillByTime_CWGSResponse() {
        }
        
        public GetPayReceiveBillByTime_CWGSResponse(System.Data.DataTable GetPayReceiveBillByTime_CWGSResult) {
            this.GetPayReceiveBillByTime_CWGSResult = GetPayReceiveBillByTime_CWGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetYW_HYGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetYW_HYGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        public GetYW_HYGSRequest() {
        }
        
        public GetYW_HYGSRequest(wlkg.GetData.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetYW_HYGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetYW_HYGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetYW_HYGSResult;
        
        public GetYW_HYGSResponse() {
        }
        
        public GetYW_HYGSResponse(System.Data.DataTable GetYW_HYGSResult) {
            this.GetYW_HYGSResult = GetYW_HYGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetYWByTime_HYGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetYWByTime_HYGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public string StartTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=1)]
        public string EndTime;
        
        public GetYWByTime_HYGSRequest() {
        }
        
        public GetYWByTime_HYGSRequest(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            this.AuthHeader = AuthHeader;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetYWByTime_HYGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetYWByTime_HYGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetYWByTime_HYGSResult;
        
        public GetYWByTime_HYGSResponse() {
        }
        
        public GetYWByTime_HYGSResponse(System.Data.DataTable GetYWByTime_HYGSResult) {
            this.GetYWByTime_HYGSResult = GetYWByTime_HYGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetYW_CWGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetYW_CWGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        public GetYW_CWGSRequest() {
        }
        
        public GetYW_CWGSRequest(wlkg.GetData.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetYW_CWGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetYW_CWGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetYW_CWGSResult;
        
        public GetYW_CWGSResponse() {
        }
        
        public GetYW_CWGSResponse(System.Data.DataTable GetYW_CWGSResult) {
            this.GetYW_CWGSResult = GetYW_CWGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetYWByTime_CWGS", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetYWByTime_CWGSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public string StartTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=1)]
        public string EndTime;
        
        public GetYWByTime_CWGSRequest() {
        }
        
        public GetYWByTime_CWGSRequest(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            this.AuthHeader = AuthHeader;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetYWByTime_CWGSResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetYWByTime_CWGSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetYWByTime_CWGSResult;
        
        public GetYWByTime_CWGSResponse() {
        }
        
        public GetYWByTime_CWGSResponse(System.Data.DataTable GetYWByTime_CWGSResult) {
            this.GetYWByTime_CWGSResult = GetYWByTime_CWGSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetYW_CWGS_CDB", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetYW_CWGS_CDBRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx")]
        public wlkg.GetData.AuthHeader AuthHeader;
        
        public GetYW_CWGS_CDBRequest() {
        }
        
        public GetYW_CWGS_CDBRequest(wlkg.GetData.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetYW_CWGS_CDBResponse", WrapperNamespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", IsWrapped=true)]
    public partial class GetYW_CWGS_CDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws-lh.lygeport.gov.cn:8080/GetDataService/WebService.asmx", Order=0)]
        public System.Data.DataTable GetYW_CWGS_CDBResult;
        
        public GetYW_CWGS_CDBResponse() {
        }
        
        public GetYW_CWGS_CDBResponse(System.Data.DataTable GetYW_CWGS_CDBResult) {
            this.GetYW_CWGS_CDBResult = GetYW_CWGS_CDBResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : wlkg.GetData.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<wlkg.GetData.WebServiceSoap>, wlkg.GetData.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetClientDataResponse wlkg.GetData.WebServiceSoap.GetClientData(wlkg.GetData.GetClientDataRequest request) {
            return base.Channel.GetClientData(request);
        }
        
        public System.Data.DataTable GetClientData(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetClientDataRequest inValue = new wlkg.GetData.GetClientDataRequest();
            inValue.AuthHeader = AuthHeader;
            wlkg.GetData.GetClientDataResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetClientData(inValue);
            return retVal.GetClientDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetClientDataResponse> wlkg.GetData.WebServiceSoap.GetClientDataAsync(wlkg.GetData.GetClientDataRequest request) {
            return base.Channel.GetClientDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetClientDataResponse> GetClientDataAsync(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetClientDataRequest inValue = new wlkg.GetData.GetClientDataRequest();
            inValue.AuthHeader = AuthHeader;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetClientDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetContractInfo_HYGSResponse wlkg.GetData.WebServiceSoap.GetContractInfo_HYGS(wlkg.GetData.GetContractInfo_HYGSRequest request) {
            return base.Channel.GetContractInfo_HYGS(request);
        }
        
        public System.Data.DataTable GetContractInfo_HYGS(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetContractInfo_HYGSRequest inValue = new wlkg.GetData.GetContractInfo_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            wlkg.GetData.GetContractInfo_HYGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetContractInfo_HYGS(inValue);
            return retVal.GetContractInfo_HYGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetContractInfo_HYGSResponse> wlkg.GetData.WebServiceSoap.GetContractInfo_HYGSAsync(wlkg.GetData.GetContractInfo_HYGSRequest request) {
            return base.Channel.GetContractInfo_HYGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetContractInfo_HYGSResponse> GetContractInfo_HYGSAsync(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetContractInfo_HYGSRequest inValue = new wlkg.GetData.GetContractInfo_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetContractInfo_HYGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetContractInfoByTime_HYGSResponse wlkg.GetData.WebServiceSoap.GetContractInfoByTime_HYGS(wlkg.GetData.GetContractInfoByTime_HYGSRequest request) {
            return base.Channel.GetContractInfoByTime_HYGS(request);
        }
        
        public System.Data.DataTable GetContractInfoByTime_HYGS(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetContractInfoByTime_HYGSRequest inValue = new wlkg.GetData.GetContractInfoByTime_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            wlkg.GetData.GetContractInfoByTime_HYGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetContractInfoByTime_HYGS(inValue);
            return retVal.GetContractInfoByTime_HYGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetContractInfoByTime_HYGSResponse> wlkg.GetData.WebServiceSoap.GetContractInfoByTime_HYGSAsync(wlkg.GetData.GetContractInfoByTime_HYGSRequest request) {
            return base.Channel.GetContractInfoByTime_HYGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetContractInfoByTime_HYGSResponse> GetContractInfoByTime_HYGSAsync(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetContractInfoByTime_HYGSRequest inValue = new wlkg.GetData.GetContractInfoByTime_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetContractInfoByTime_HYGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetContractInfo_CWGSResponse wlkg.GetData.WebServiceSoap.GetContractInfo_CWGS(wlkg.GetData.GetContractInfo_CWGSRequest request) {
            return base.Channel.GetContractInfo_CWGS(request);
        }
        
        public System.Data.DataTable GetContractInfo_CWGS(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetContractInfo_CWGSRequest inValue = new wlkg.GetData.GetContractInfo_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            wlkg.GetData.GetContractInfo_CWGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetContractInfo_CWGS(inValue);
            return retVal.GetContractInfo_CWGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetContractInfo_CWGSResponse> wlkg.GetData.WebServiceSoap.GetContractInfo_CWGSAsync(wlkg.GetData.GetContractInfo_CWGSRequest request) {
            return base.Channel.GetContractInfo_CWGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetContractInfo_CWGSResponse> GetContractInfo_CWGSAsync(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetContractInfo_CWGSRequest inValue = new wlkg.GetData.GetContractInfo_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetContractInfo_CWGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetContractInfoByTime_CWGSResponse wlkg.GetData.WebServiceSoap.GetContractInfoByTime_CWGS(wlkg.GetData.GetContractInfoByTime_CWGSRequest request) {
            return base.Channel.GetContractInfoByTime_CWGS(request);
        }
        
        public System.Data.DataTable GetContractInfoByTime_CWGS(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetContractInfoByTime_CWGSRequest inValue = new wlkg.GetData.GetContractInfoByTime_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            wlkg.GetData.GetContractInfoByTime_CWGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetContractInfoByTime_CWGS(inValue);
            return retVal.GetContractInfoByTime_CWGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetContractInfoByTime_CWGSResponse> wlkg.GetData.WebServiceSoap.GetContractInfoByTime_CWGSAsync(wlkg.GetData.GetContractInfoByTime_CWGSRequest request) {
            return base.Channel.GetContractInfoByTime_CWGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetContractInfoByTime_CWGSResponse> GetContractInfoByTime_CWGSAsync(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetContractInfoByTime_CWGSRequest inValue = new wlkg.GetData.GetContractInfoByTime_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetContractInfoByTime_CWGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetPayReceiveBill_HYGSResponse wlkg.GetData.WebServiceSoap.GetPayReceiveBill_HYGS(wlkg.GetData.GetPayReceiveBill_HYGSRequest request) {
            return base.Channel.GetPayReceiveBill_HYGS(request);
        }
        
        public System.Data.DataTable GetPayReceiveBill_HYGS(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetPayReceiveBill_HYGSRequest inValue = new wlkg.GetData.GetPayReceiveBill_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            wlkg.GetData.GetPayReceiveBill_HYGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetPayReceiveBill_HYGS(inValue);
            return retVal.GetPayReceiveBill_HYGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBill_HYGSResponse> wlkg.GetData.WebServiceSoap.GetPayReceiveBill_HYGSAsync(wlkg.GetData.GetPayReceiveBill_HYGSRequest request) {
            return base.Channel.GetPayReceiveBill_HYGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBill_HYGSResponse> GetPayReceiveBill_HYGSAsync(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetPayReceiveBill_HYGSRequest inValue = new wlkg.GetData.GetPayReceiveBill_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetPayReceiveBill_HYGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetPayReceiveBillByTime_HYGSResponse wlkg.GetData.WebServiceSoap.GetPayReceiveBillByTime_HYGS(wlkg.GetData.GetPayReceiveBillByTime_HYGSRequest request) {
            return base.Channel.GetPayReceiveBillByTime_HYGS(request);
        }
        
        public System.Data.DataTable GetPayReceiveBillByTime_HYGS(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetPayReceiveBillByTime_HYGSRequest inValue = new wlkg.GetData.GetPayReceiveBillByTime_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            wlkg.GetData.GetPayReceiveBillByTime_HYGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetPayReceiveBillByTime_HYGS(inValue);
            return retVal.GetPayReceiveBillByTime_HYGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBillByTime_HYGSResponse> wlkg.GetData.WebServiceSoap.GetPayReceiveBillByTime_HYGSAsync(wlkg.GetData.GetPayReceiveBillByTime_HYGSRequest request) {
            return base.Channel.GetPayReceiveBillByTime_HYGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBillByTime_HYGSResponse> GetPayReceiveBillByTime_HYGSAsync(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetPayReceiveBillByTime_HYGSRequest inValue = new wlkg.GetData.GetPayReceiveBillByTime_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetPayReceiveBillByTime_HYGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetPayReceiveBill_CWGSResponse wlkg.GetData.WebServiceSoap.GetPayReceiveBill_CWGS(wlkg.GetData.GetPayReceiveBill_CWGSRequest request) {
            return base.Channel.GetPayReceiveBill_CWGS(request);
        }
        
        public System.Data.DataTable GetPayReceiveBill_CWGS(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetPayReceiveBill_CWGSRequest inValue = new wlkg.GetData.GetPayReceiveBill_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            wlkg.GetData.GetPayReceiveBill_CWGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetPayReceiveBill_CWGS(inValue);
            return retVal.GetPayReceiveBill_CWGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBill_CWGSResponse> wlkg.GetData.WebServiceSoap.GetPayReceiveBill_CWGSAsync(wlkg.GetData.GetPayReceiveBill_CWGSRequest request) {
            return base.Channel.GetPayReceiveBill_CWGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBill_CWGSResponse> GetPayReceiveBill_CWGSAsync(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetPayReceiveBill_CWGSRequest inValue = new wlkg.GetData.GetPayReceiveBill_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetPayReceiveBill_CWGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetPayReceiveBillByTime_CWGSResponse wlkg.GetData.WebServiceSoap.GetPayReceiveBillByTime_CWGS(wlkg.GetData.GetPayReceiveBillByTime_CWGSRequest request) {
            return base.Channel.GetPayReceiveBillByTime_CWGS(request);
        }
        
        public System.Data.DataTable GetPayReceiveBillByTime_CWGS(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetPayReceiveBillByTime_CWGSRequest inValue = new wlkg.GetData.GetPayReceiveBillByTime_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            wlkg.GetData.GetPayReceiveBillByTime_CWGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetPayReceiveBillByTime_CWGS(inValue);
            return retVal.GetPayReceiveBillByTime_CWGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBillByTime_CWGSResponse> wlkg.GetData.WebServiceSoap.GetPayReceiveBillByTime_CWGSAsync(wlkg.GetData.GetPayReceiveBillByTime_CWGSRequest request) {
            return base.Channel.GetPayReceiveBillByTime_CWGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetPayReceiveBillByTime_CWGSResponse> GetPayReceiveBillByTime_CWGSAsync(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetPayReceiveBillByTime_CWGSRequest inValue = new wlkg.GetData.GetPayReceiveBillByTime_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetPayReceiveBillByTime_CWGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetYW_HYGSResponse wlkg.GetData.WebServiceSoap.GetYW_HYGS(wlkg.GetData.GetYW_HYGSRequest request) {
            return base.Channel.GetYW_HYGS(request);
        }
        
        public System.Data.DataTable GetYW_HYGS(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetYW_HYGSRequest inValue = new wlkg.GetData.GetYW_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            wlkg.GetData.GetYW_HYGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetYW_HYGS(inValue);
            return retVal.GetYW_HYGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetYW_HYGSResponse> wlkg.GetData.WebServiceSoap.GetYW_HYGSAsync(wlkg.GetData.GetYW_HYGSRequest request) {
            return base.Channel.GetYW_HYGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetYW_HYGSResponse> GetYW_HYGSAsync(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetYW_HYGSRequest inValue = new wlkg.GetData.GetYW_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetYW_HYGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetYWByTime_HYGSResponse wlkg.GetData.WebServiceSoap.GetYWByTime_HYGS(wlkg.GetData.GetYWByTime_HYGSRequest request) {
            return base.Channel.GetYWByTime_HYGS(request);
        }
        
        public System.Data.DataTable GetYWByTime_HYGS(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetYWByTime_HYGSRequest inValue = new wlkg.GetData.GetYWByTime_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            wlkg.GetData.GetYWByTime_HYGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetYWByTime_HYGS(inValue);
            return retVal.GetYWByTime_HYGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetYWByTime_HYGSResponse> wlkg.GetData.WebServiceSoap.GetYWByTime_HYGSAsync(wlkg.GetData.GetYWByTime_HYGSRequest request) {
            return base.Channel.GetYWByTime_HYGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetYWByTime_HYGSResponse> GetYWByTime_HYGSAsync(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetYWByTime_HYGSRequest inValue = new wlkg.GetData.GetYWByTime_HYGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetYWByTime_HYGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetYW_CWGSResponse wlkg.GetData.WebServiceSoap.GetYW_CWGS(wlkg.GetData.GetYW_CWGSRequest request) {
            return base.Channel.GetYW_CWGS(request);
        }
        
        public System.Data.DataTable GetYW_CWGS(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetYW_CWGSRequest inValue = new wlkg.GetData.GetYW_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            wlkg.GetData.GetYW_CWGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetYW_CWGS(inValue);
            return retVal.GetYW_CWGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetYW_CWGSResponse> wlkg.GetData.WebServiceSoap.GetYW_CWGSAsync(wlkg.GetData.GetYW_CWGSRequest request) {
            return base.Channel.GetYW_CWGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetYW_CWGSResponse> GetYW_CWGSAsync(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetYW_CWGSRequest inValue = new wlkg.GetData.GetYW_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetYW_CWGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetYWByTime_CWGSResponse wlkg.GetData.WebServiceSoap.GetYWByTime_CWGS(wlkg.GetData.GetYWByTime_CWGSRequest request) {
            return base.Channel.GetYWByTime_CWGS(request);
        }
        
        public System.Data.DataTable GetYWByTime_CWGS(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetYWByTime_CWGSRequest inValue = new wlkg.GetData.GetYWByTime_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            wlkg.GetData.GetYWByTime_CWGSResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetYWByTime_CWGS(inValue);
            return retVal.GetYWByTime_CWGSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetYWByTime_CWGSResponse> wlkg.GetData.WebServiceSoap.GetYWByTime_CWGSAsync(wlkg.GetData.GetYWByTime_CWGSRequest request) {
            return base.Channel.GetYWByTime_CWGSAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetYWByTime_CWGSResponse> GetYWByTime_CWGSAsync(wlkg.GetData.AuthHeader AuthHeader, string StartTime, string EndTime) {
            wlkg.GetData.GetYWByTime_CWGSRequest inValue = new wlkg.GetData.GetYWByTime_CWGSRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.StartTime = StartTime;
            inValue.EndTime = EndTime;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetYWByTime_CWGSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wlkg.GetData.GetYW_CWGS_CDBResponse wlkg.GetData.WebServiceSoap.GetYW_CWGS_CDB(wlkg.GetData.GetYW_CWGS_CDBRequest request) {
            return base.Channel.GetYW_CWGS_CDB(request);
        }
        
        public System.Data.DataTable GetYW_CWGS_CDB(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetYW_CWGS_CDBRequest inValue = new wlkg.GetData.GetYW_CWGS_CDBRequest();
            inValue.AuthHeader = AuthHeader;
            wlkg.GetData.GetYW_CWGS_CDBResponse retVal = ((wlkg.GetData.WebServiceSoap)(this)).GetYW_CWGS_CDB(inValue);
            return retVal.GetYW_CWGS_CDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wlkg.GetData.GetYW_CWGS_CDBResponse> wlkg.GetData.WebServiceSoap.GetYW_CWGS_CDBAsync(wlkg.GetData.GetYW_CWGS_CDBRequest request) {
            return base.Channel.GetYW_CWGS_CDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<wlkg.GetData.GetYW_CWGS_CDBResponse> GetYW_CWGS_CDBAsync(wlkg.GetData.AuthHeader AuthHeader) {
            wlkg.GetData.GetYW_CWGS_CDBRequest inValue = new wlkg.GetData.GetYW_CWGS_CDBRequest();
            inValue.AuthHeader = AuthHeader;
            return ((wlkg.GetData.WebServiceSoap)(this)).GetYW_CWGS_CDBAsync(inValue);
        }
    }
}
